### ISSUE TITLE
Can't apply more then one effect

### ISSUE THREAD

**Issue by LooxLuchs** [TathanDev/MoreOraxenMechanics#2]
Hey, I can't apply more then one effect mechanic to the item. Only one effect will be applied to the enemy.

```
  Mechanics:
    effect:
      effect: hunger
      duration: 500
      amplifier: 6 
    durability:
      value: 1766
    effect:
      effect: nausea
      duration: 500
      amplifier: 5
```
